-- Supabase License Table & Schema Setup Script
-- Execute this script in your Supabase SQL Editor to prepare the database for the licensing API.

-- 1. Drop the table if it already exists to start fresh
DROP TABLE IF EXISTS public.licenses;

-- 2. Create the licenses table
CREATE TABLE public.licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    activation_code TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'expired')),
    expires_at TIMESTAMP WITH TIME ZONE NULL, -- NULL means lifetime license
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Disable Row Level Security (RLS) to guarantee the API key has read permissions
ALTER TABLE public.licenses DISABLE ROW LEVEL SECURITY;

-- 4. Insert clean test licenses
INSERT INTO public.licenses (email, activation_code, status, expires_at)
VALUES 
('test@example.com', 'ACT-123', 'active', '2026-12-31 23:59:59+00'), -- Active until Dec 31, 2026
('test@gmail.com', 'ASD123', 'active', NULL),                          -- Active forever (lifetime)
('expired@example.com', 'EXP-123', 'active', '2026-06-01 00:00:00+00'); -- Expired on June 1, 2026
